version: 2.1

orbs:
  netflex: netflex/netflex-deploy@1.0.12

jobs:
  checkout:
    docker:
      - image: circleci/node:latest
    steps:
      - netflex/pull

  composer:
    docker:
      - image: circleci/php:latest
    steps:
      - netflex/composer

  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: "Set build env variable(s)"
          command: echo 'export NODE_ENV="production"' >> $BASH_ENV
      - netflex/build

  create_site:
    docker:
      - image: circleci/node:latest
    steps:
      - netflex/create_site

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - netflex/deploy

workflows:
  version: 2
  deployment:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - dev
                - stage
                - master
      - composer:
          requires:
            - checkout
          context: Apility Github
      - build:
          requires:
            - checkout
      - create_site:
          requires:
            - checkout
          filters:
            branches:
              only:
                - dev
                - stage
      - deploy:
          requires:
            - build
            - composer
